kadai01.kt
shinonome-inc/mobile_takafumi pull request #1
Opened 2020-06-30 08:15 UTC by taka0815basket

2020-06-30 08:39 UTC, mcz9mm requested changes
コメントしました！

2020-06-30 08:39 UTC, mcz9mm commented on kadai01.kt
> +var Int = 2000
これは型の`Int`と変数名としての`Int`どっちの意味で書いたかな？
誤解を産んでしまう変数名なので適切な名前に変えてください。

2020-06-30 08:39 UTC, mcz9mm commented on kadai01.kt
> +   if(Int % 400 == 0){
main関数からジャンケンの判定を行うメソッドを作成してください

```
fun main() {
    println(isLeap(year: 2000)) // true
    println(isLeap(year:  1209)) // false
}
```

2020-06-30 08:39 UTC, mcz9mm commented on kadai01.kt
> +# mobile_takafumi
これ、READMEからコピぺした？w

2020-06-30 13:03 UTC, taka0815basket commented on kadai01.kt
> +# mobile_takafumi
READMEもメモしたやつからコピペしました！

2020-06-30 13:07 UTC, taka0815basket commented on kadai01.kt
> +var Int = 2000
変数名としてわかりやすいようにIntを使いました。
変数名をnumIntに修正しました。
これで、提出もう一度提出したほうがいいですか？

2020-07-01 12:08 UTC, taka0815basket commented
@mcz9mm  レビューに指摘されたことを修正しました。
ローカルで開発する環境整えたので、設定ファイルなども追加されてます。
再レビューお願いします。

2020-07-01 13:24 UTC, mcz9mm commented
これは直せそうかな？
mainで書いてるやつを関数化するの
https://github.com/shinonome-inc/mobile_takafumi/pull/1#discussion_r447510077

2020-07-06 09:22 UTC, taka0815basket commented
slackで送ってもらったサイトを参考に関数のところをやっていて遅れてしまいまいました。
あっているか心配なんですけど、再レビューお願いします。

2020-07-06 09:38 UTC, mcz9mm requested changes
コメント返しました

2020-07-06 09:38 UTC, mcz9mm commented on src/kadai01.kt
> +fun main(args: Array<Int>) {
この前も伝えたと思うけど、
```
fun main() {
    println(isLeap(year: 2000)) // true
    println(isLeap(year:  1209)) // false
}
```

ジャンケン判定を行う関数を作成してmain()の処理で呼び出せるように直してみてください！

やること
・関数の作成
・引数の追加
・戻り値の設定

2020-07-06 09:38 UTC, mcz9mm commented on src/kadai01.kt
> +fun main(args: Array<Int>) {
ヒント

```
fun main() {
   Foo() // Foo中のコードが呼び出されprintlinが実行される
}

fun Foo() {
   println("Hoge")
}
```

2020-07-06 09:38 UTC, mcz9mm commented on src/kadai01.kt
> +fun main(args: Array<Int>) {
ヒント　引数

https://dogwood008.github.io/kotlin-web-site-ja/docs/reference/functions.html#%E3%83%91%E3%83%A9%E3%83%A1%E3%83%BC%E3%82%BF%E3%83%BC

2020-07-07 10:25 UTC, taka0815basket commented
レビューで指摘されたことを送ってもらったサイトなどで修正しました。
再レビューお願いします。

2020-07-07 10:52 UTC, mcz9mm approved these changes
OKです！

2020-07-07 10:52 UTC, merged