Kadai02.kt
shinonome-inc/mobile_takafumi pull request #3
Opened 2020-07-11 11:26 UTC by taka0815basket

2020-07-11 11:27 UTC, taka0815basket commented
課題０２ができました。
レビューお願いします。

2020-07-12 03:56 UTC, ryo1443 requested changes
レビューしました！
全体的に、何もない行は消して、役割の異なる処理の間だけ行を空けると良いと思います。

2020-07-12 03:56 UTC, ryo1443 commented on src/kadai02.kt
> +    }
処理は良いと思います！

2020-07-12 03:56 UTC, ryo1443 commented on src/kadai02.kt
> +fun janken ():Int {
要項では`janken()`に引数を与えて処理を行うよう示唆されているので、そのように変更出来ますか？少しコードを変更すれば出来ると思います。

関数に返り値が定義されていますが、この処理だと必要ありません。返り値を省略する関数も定義が可能です。

2020-07-12 03:56 UTC, ryo1443 commented on src/kadai02.kt
> +}
要項では"Hand"や"Result"というクラスが求められているので、従うようにしましょう。この箇所以外のおいてもクラスやメソッド、変数の名前は要項に従うと良いと思います。

　コードの可読性を上げるために、名前やスぺースの開け方には規則が存在しています。具体的には、クラス名はキャメルケース（各単語の頭文字だけ大文字にする。例：EnumHand）にするなど。以下に詳細を載せていますが、最初から全てを把握するのは難しいと思うので「命名スタイル」の上4つだけからでも実践すると良いと思います。
https://dogwood008.github.io/kotlin-web-site-ja/docs/reference/coding-conventions.html

2020-07-12 03:56 UTC, ryo1443 commented on src/kadai02.kt
> +    }
```
when (r) {
        0 -> println("相手の手は${enumhand.Gu}")
        1 -> println("相手の手は${enumhand.Ti}")
        else -> println("相手の手は${enumhand.Pa}")
    }
```
when式や文字列テンプレートを使えば、よりスッキリ書くことも出来ます。

2020-07-12 03:56 UTC, ryo1443 commented on src/kadai02.kt
> +    var r = (0..2).random()
この2変数は処理の中で再代入されることは無いので、valにしましょう。これは、プログラムをより堅牢にするためです。原則としてvalを使用すると覚えておくと良いと思います。

2020-07-13 09:07 UTC, taka0815basket commented
修正しました。
ifのところは文字列テンプレートを使って短くしてみました。
再レビューお願いします。

2020-07-13 09:47 UTC, ryo1443 requested changes
レビューしました。前回よりもコードが見やすくなって良いと思います！あともう少しです！

2020-07-13 09:47 UTC, ryo1443 commented on src/kadai02.kt
>      }
スッキリしてとても良いと思います！
ちなみに…if式は必ずしもブロック{}を取る必要はなく、
```
if (r == 0) println("wawa")
else if (r == 1) println("hoho")
else println("hoge")
```
のようにも書けたりします。

2020-07-13 09:47 UTC, ryo1443 commented on src/kadai02.kt
> +    janken(0)
要件通り、関数に引数が渡るところから処理が始まるので良いと思います！しかし、このままだとjankenに入力した0は正しく機能せず、結局ターミナルから数字を打ち込む羽目になってしまいます。関数に渡した数字で、正しく処理が出来るように改善してみてください！あと一歩です。

2020-07-13 14:23 UTC, taka0815basket commented
修正しました。
再レビューお願いします。

2020-07-14 02:25 UTC, ryo1443 requested changes
コメントしました。通知が来ないので、修正した旨はslackでも伝えてください！また、レビュー内容に一言でもコメントを添えてあげると、レビュー側は助かります！

2020-07-14 02:25 UTC, ryo1443 commented on src/kadai02.kt
> -
xという変数が重複していたが故に、前回のコードでは関数に引数を渡しても無意味だったというのが結論です！このコードを消したことによってそれが実現できましたね。

2020-07-14 02:25 UTC, ryo1443 commented on src/kadai02.kt
> +    janken(x ?. toInt()!!)
このままjanken(0)のようにだけ書いて提出してくれても全然良かったですが、ターミナルから打ち込むならばUXが向上するので、良い試みだと思います!

一つ問題があるとすれば、`janken(x ?. toInt()!!)`の部分です。`toInt()`が使われていますが、一行上からInt型であることは確定しているので、必要ありません。また、`!!`という演算子はnullでなければ処理を行い、nullならばエラーを返すというもので、結構危険です。原則として使うことを控えると良いと思います。もしnullチェックを行いたいならば、
```
if (x != null) {

}
```
のように書いたりすると良いと思います。詳しくは以下で。
https://maku77.github.io/kotlin/basic/handle-null.html

2020-07-14 04:35 UTC, taka0815basket commented
最後の関数のjankenを使うところをnull使って修正しました。
前回はslackのほうで言わなくてすみませんでした。
再レビューお願いします。

2020-07-14 04:43 UTC, ryo1443 reviewed
全体的に無駄が少なくなって、凄く良いコードになりました！良いと思います！

2020-07-14 04:43 UTC, ryo1443 commented on src/kadai02.kt
> +fun janken(x: Int) {
こういう細かいスペースで見やすさが変わってくるので、大事にしましょう！

2020-07-14 04:43 UTC, ryo1443 commented on src/kadai02.kt
> +    }
良いと思います！`!!`には注意で！

2020-07-14 04:44 UTC, ryo1443 approved these changes

2020-07-14 06:51 UTC, mcz9mm requested changes
コメントしました！

2020-07-14 06:51 UTC, mcz9mm commented on src/kadai02.kt
> +    val r = (0..2).random()
このランダム値からenumの`Hand `を生成できるようにしてみてください

2020-07-14 06:51 UTC, mcz9mm commented on src/kadai02.kt
> +enum class Hand{
このようにenumにintを定義することができます
```
enum class Hand(val rawValue :Int)  {
    Gu(0),
    Ti(1),
    Pa(2)
}
```

2020-07-14 06:51 UTC, mcz9mm commented on src/kadai02.kt
> +    val r = (0..2).random()
ここを参考に
https://github.com/shinonome-inc/mobile_takafumi/pull/3/files#diff-3f0396fc2634ed7b96839b42d0dd793dR1

2020-07-14 06:51 UTC, mcz9mm commented on src/kadai02.kt
> +fun janken(x: Int) {
引数にとるパラメータは`Int`ではなく`Hand `を受け取るようにしてください

2020-07-14 07:00 UTC, mcz9mm commented on src/kadai02.kt
> +    if(r == 0){
when構文を使うとスッキリよ
```
when (r) {
    0 -> {
        println("0")
    }
    1 -> {
        println("1")
    }
    2 -> {
        println("2")
    }
    else -> {
        println("else")
    }
}

2020-07-15 12:22 UTC, taka0815basket commented
enumクラスのHandとifをwhenに変えました。
janken関数の引数をHandに変えてみました。
再レビューお願いします。

2020-07-16 00:34 UTC, mcz9mm approved these changes
オッケーです！
１点Tipsを書いたのでそこを確認して次へ進んでください。

2020-07-16 00:34 UTC, mcz9mm commented on src/kadai02.kt
>      if(x == 1){
Tips:

さらに良くするとすればenumの初期化を工夫すると↓のような感じで
IntからHandを生成することができます。

```
enum class Hand(val rawValue: Int) {
    Gu(0),
    Ti(1),
    Pa(2);

    companion object {
        fun init(type: Int) : Hand? = when(type) {
            0 -> Gu
            1 -> Ti
            2 -> Pa
            else -> null
        }
    }
}

   val gu = Hand.init(0)
   print(gu) //Gu
   val ti = Hand.init(1)
   print(ti) //Ti
   val pa = Hand.init(2)
   print(pa) //Pa
   val foo = Hand.init(3)
   print(foo)//null
```

参考
https://shoheohtani.blogspot.com/2019/01/kotlin-enum.html

2020-07-16 00:34 UTC, merged