first
shinonome-inc/mobile_takafumi pull request #5
Opened 2020-09-08 08:35 UTC by taka0815basket

2020-09-08 08:36 UTC, taka0815basket commented
課題3ができたのでレビューをお願いいたします。

2020-09-08 16:08 UTC, ryo1443 reviewed
取り敢えず、コーディング規則や読みやすさに欠ける点を指摘させていただきました。
このプログラムではアプリは正常に動かないので、そこ含めて修正してみてください。
分からない事が有れば何でも聞いて大丈夫です。（漠然としてても）
Slackで連絡をくれると気づきやすいです。

2020-09-08 16:08 UTC, ryo1443 commented on kadai03/app/src/main/java/com/example/leapyear/MainActivity.kt
> +
"{"の次の行は空けるのか空けないのかを統一しましょう。
今回の場合、10行目11行目で空いていないので不自然に見えます。

2020-09-08 16:08 UTC, ryo1443 commented on kadai03/app/src/main/java/com/example/leapyear/MainActivity.kt
> +            val EditText = editTextNumber.text
変数の定義は余計な行を空けず、ひとまとめで良いです。
また、"="の前後はスペースを入れましょう。

2020-09-08 16:08 UTC, ryo1443 commented on kadai03/app/src/main/java/com/example/leapyear/MainActivity.kt
> +                }
"("の前後や"{"の前後はスペースを空けましょう。
変数やメソッド名はローワーキャメルケースで宣言します。（クラス名はアッパーキャメルケース）
リソースに関する命名（layoutファイルの名前やコンポーネントid）にはスネークケースを使います

2020-09-08 16:08 UTC, ryo1443 commented on kadai03/app/src/main/java/com/example/leapyear/MainActivity.kt
> +        }
余計な行は消しましょう

2020-09-08 16:08 UTC, ryo1443 commented on kadai03/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/editTextNumber"
スネークケースまたは一単語(editText)が自然です

2020-09-09 13:50 UTC, taka0815basket commented
課題3の修正ができたので再レビューお願いいたします。
今回はアプリが正常に動きました。指摘されたコーディング規則と見易さも直してみました。

2020-09-10 02:14 UTC, ryo1443 reviewed
よくできていると思います！もう少しです

2020-09-10 02:14 UTC, ryo1443 commented on kadai03/app/src/main/java/com/example/leapyear/MainActivity.kt
> +            val EditText = editTextNumber.text.toString()
変数名の頭文字は小文字が原則です。Android Studioではグレーの下線でそういったミスを指摘してくれます

2020-09-10 02:14 UTC, ryo1443 commented on kadai03/app/src/main/java/com/example/leapyear/MainActivity.kt
> +            val EditText = editTextNumber.text.toString()
一つのウィジェットは一つの変数で管理した方が良いです。
editText = findViewById<EditText>(R.id.editText)
使うときは、
editText.textやeditText.errorなどとして使います。これらそれぞれを変数に格納すると混乱を招きやすいです。

2020-09-10 02:14 UTC, ryo1443 commented on kadai03/app/src/main/java/com/example/leapyear/MainActivity.kt
> +           }
ロジックは大丈夫だと思います！
結果については、一つ一つ変数に置かなくても
editText.text = ～～～
として、直接ウィジェットから操作した方が冗長にならないので良いです。
また、使用する文字列はリソース化しなくても大丈夫です。（あくまで複数の言語に対応するアプリの時効果を発揮する機能なので）

2020-09-10 03:51 UTC, ryo1443 commented on kadai03/app/src/main/java/com/example/leapyear/MainActivity.kt
> +           }
editText→textViewですね、すいません。

2020-09-10 10:01 UTC, taka0815basket commented
修正したので再レビューをお願いいたします。
19行目の変数を消したことで発生したエラーを改善しました。

2020-09-10 10:45 UTC, ryo1443 reviewed
多分大丈夫だと思います。この後はかおるさんに聞いてみてください。

2020-09-10 10:45 UTC, ryo1443 commented on kadai03/app/src/main/java/com/example/leapyear/MainActivity.kt
> +            val editText = findViewById<EditText>(R.id.editText)
今回は`button.setOnClickListener`の外でもここで定義している変数は使われているので、わざわざ中で定義する必要はありません。17,18行目とまとめると良いと思います。
先ほど言い忘れましたが、ビューのコンポーネントを扱う変数の名前（今回だとbuttonやeditTextという変数名）はそれに付与したid名と同じにすると良いです。参考までに。

2020-09-10 10:45 UTC, ryo1443 commented on kadai03/app/src/main/java/com/example/leapyear/MainActivity.kt
> +                   textView.text = "$year is not leap year"
スッキリして見やすいですね

2020-09-10 23:58 UTC, mcz9mm requested changes
コメントしました

2020-09-10 23:58 UTC, mcz9mm commented on kadai03/app/src/main/java/com/example/leapyear/MainActivity.kt
> +        val button = findViewById<Button>(R.id.button)
findViewByIdは最近だと使わずにxml側のパーツでID(ユニーク)を設定すると
参照できるようになるので直しましょう。

こうゆうのが不要になる
```
val editText = findViewById<EditText>(R.id.editText)
```

2020-09-10 23:58 UTC, mcz9mm commented on kadai03/app/src/main/java/com/example/leapyear/MainActivity.kt
> +        val button = findViewById<Button>(R.id.button)
<img width="407" alt="スクリーンショット 2020-09-11 8 55 39" src="https://user-images.githubusercontent.com/11751495/92827248-997b4900-f40c-11ea-80fe-b24ce9045cc2.png">
<img width="410" alt="スクリーンショット 2020-09-11 8 55 33" src="https://user-images.githubusercontent.com/11751495/92827252-9aac7600-f40c-11ea-8dfd-9bb5ea7e1812.png">

2020-09-10 23:58 UTC, mcz9mm commented on kadai03/app/src/main/java/com/example/leapyear/MainActivity.kt
> +        val button = findViewById<Button>(R.id.button)
そうすると`findViewById`で定数を宣言する必要はなくなります

2020-09-11 09:33 UTC, taka0815basket commented
修正したので再レビューをお願いします。

2020-09-11 09:37 UTC, merged

2020-09-11 09:37 UTC, mcz9mm commented
LGTM!

2020-09-11 09:38 UTC, mcz9mm commented
![](https://media.giphy.com/media/iOMSfTen1pZUPTx2QF/giphy.gif)