Create kadai04
shinonome-inc/mobile_takafumi pull request #6
Opened 2020-09-14 06:54 UTC by taka0815basket

課題４ができたのでレビューをお願いします。

2020-09-15 05:35 UTC, taka0815basket commented
消えてたファイルを追加しました。確認をお願いします。

2020-09-21 16:49 UTC, taka0815basket commented
アニメーションの追加ができたので確認をお願いいたします。

2020-09-23 01:44 UTC, ryo1443 reviewed
全体として、中カッコ・コロンの前後にはスペースを入れるようにしましょう。

2020-09-23 01:44 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +        var frame3 = resources.getDrawable(R.drawable.paper)
android studioで表示されているように、この使い方の`getDrawable`は廃止されています。マウスカーソルを合わせて詳細を見ると`ResourcesCompat`を使えとあるので、`ResourcesCompat.getDrawable(resources, R.drawable.rock, null)`が正しい形となると思います。
しかし、そもそもこのように慣れないメソッドを使わずとも、単純にアニメーションをstopさせた後、該当する画像をimageViewに差し込めば済むのではないかと思いました。

2020-09-23 01:44 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +        ad.addFrame(frame3,50)
アニメーションの最後のフレームに、押したボタンの画像を挿入しているという意味ですよね？

2020-09-23 01:44 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
>          }
今のままでは一度しか画像のロールが起こらないので、少し書き換えてボタンを押すたびにロールさせるようにしてあげてください！

2020-09-23 01:44 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
>          }
また、中カッコの前には空白を入れるのがセオリーです

2020-09-23 01:44 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +        var ad = AnimationDrawable()
`ad`という変数の名前では後々理解ぱっと理解できないという事態が発生しうるので、`animationDrawable`など分かりやすい変数名を推奨します！

2020-09-27 15:06 UTC, taka0815basket commented
前回のレビューで指摘をいただいた個所を修正しました。
確認をお願いいたします。

2020-09-28 04:53 UTC, ryo1443 reviewed
アクティビティを移して結果を表示させるのはアリですが、ラグがあったりする点でclassroomのサンプルを再現してるかといわれると微妙だと思います。
アクティビティを遷移させる課題は後々出てくるので、その時に今の実装を生かして見てください。今回はアクティビティを移さずに行う方法を模索しましょう！
アルゴリズムとしては、「クリックされたら画像がロール→結果を表示させる」を考えてみてください。そうすると何回もじゃんけんが出来るようになると思います。

2020-09-28 04:53 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +        var frame3 = ResourcesCompat.getDrawable ( resources,R.drawable.paper,null )
変数名の頭文字は小文字という事と、今回はこれらの変数に書き換えが無いのでvalを使用するという事に注意してください！
ちなみに前者は灰色の下線で、後者は黄色い塗りつぶしで教えてくれます

2020-09-28 04:53 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
>          }
細かいですが、,のあとはスペースを入れましょう

2020-09-28 04:53 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +        paper.setOnClickListener { onJankenBottonTapped ( it ) }
これはラムダ式という記法になりますが、中カッコの前後にスペースを入れるだけで中身は普通で大丈夫です。
`{ onJankenBottonTapped(it) }`のように

2020-09-28 04:53 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
>      }
アクティビティを移す方法はあってます！が、今回は別のやり方を考えましょう(UXと要件的に）

2020-09-29 08:11 UTC, taka0815basket commented
レビューで指摘をいただいた点を修正して要件を満たせるようにしました。画面を２枚にして毎回同じ画面にするのは少しずるいような気がしましたが、それを含めて確認をお願いします。

2020-09-30 01:23 UTC, ryo1443 reviewed
レビューしました！たかふみさんがおっしゃる通り、改善の余地ありです！
長丁場になりますがいつでも相談に乗るので頑張りましょう！

2020-09-30 01:23 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +
2行以上の余計な空白は消しましょう。

2020-09-30 01:23 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +        val gameResult = (cpHand - myHand + 3) % 3
美しいです！

2020-09-30 01:23 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
>      }
MainActivity2もMainActivityと全く同じコードなので、無駄を感じますよね？
また、前回言ったようにやはりアクティビティを移すのは要件的にも微妙です。
一つのアクティビティの中でonCreate等を二回実行させるのはおそらく難しいので、やはりロジックで解決する他無いと思います。

2020-09-30 01:23 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +        }
ボタンがクリックされたらアニメーションが起こるようにするには
https://developer.android.com/guide/topics/graphics/drawable-animation?hl=ja
の中段のコードを参考にすればいけるはずです。
止め方に工夫が必要になると思うので、頑張りましょう。

2020-10-12 11:20 UTC, ryo1443 reviewed
取り敢えず何度もロールできたかどうか教えてください

2020-10-12 11:20 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +        }
jankenAnimation.stop()
janken(~~)
jankenAnimation.start()
として、janken()の中の画像のセットを一旦止めAnimationListのoneshotをtrueにしてあげると多分何回もリピートすると思います。
何回も出来なかった理由はボタンをクリックしたらアニメーションが開始されるコードが無いという事と、setBackgroundImageでアニメーションとは別に画像が上から覆いかぶさっていたからだと思います。
結果はアニメーションを追加で差し込む形にしなければなりません。
これで何度もリピートするようになるので、あとはテキストやその他も諸々の帳尻合わせをするだけです！

2020-10-22 14:43 UTC, taka0815basket commented
ジャンケンの処理だけをとりあえず完成で来たので確認をお願いいたします。

2020-10-23 13:31 UTC, ryo1443 reviewed
それっぽくなってとても良いと思います！
コメントアウトした行は消しても大丈夫です。
次のステップとして、ボタンを連打するとロールが何度もリセットしてしまう現象を直しましょう！そう難しくはないと思います。

2020-10-23 17:22 UTC, taka0815basket commented
ボタンを連打しても処理が実行できるようにしました。また、アニメーションを使い部分をボタンを押したときに実装できるように書いてみました。確認をよろしくお願いいたします。

2020-10-25 12:17 UTC, ryo1443 reviewed
全体として、二行以上の余白は一行にしたり左括弧の次はスペースを入れないように統一したリを徹底しましょう！

2020-10-25 12:17 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +            enemyHand.setImageResource(R.drawable.rock)
余白は詰めましょう！

2020-10-25 12:17 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +        scissors.isClickable = false
しっかりクリックが止まってるので良いと思います！

2020-10-25 12:17 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +    }
以前と挙動が全く同じなので、どこか修正の必要があると思います！ですが、もうちょいです

2020-10-26 14:09 UTC, taka0815basket commented
AlphaAnimationでのアニメーションが動くようになりました。確認をお願いします。

2020-10-27 03:07 UTC, ryo1443 reviewed
おおむね良い気がします！フェードの時間だけ色々弄ってそれっぽくしてあげて下さい
次はかおるさんで大丈夫です

2020-10-27 03:07 UTC, ryo1443 commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +            fadeInAnimation.duration = 100
今のままだとフェードが短すぎてよく分からないので、1000msとかの方が良い気がします！
試してみてください

2020-10-27 06:41 UTC, mcz9mm requested changes
コメントしました！

2020-10-27 06:41 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +enum class handType(val n: Int) {
enumやclass名は大文字スタートの方が良いね。

`HandType `変数として扱う際には`handType`でも良いけど

2020-10-27 06:41 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +            when (i % 3) {
このへん、せっかくenum作ったのに使ってないの勿体無いね
whenはenumも使えるので変換して使ってあげよう。
今回であればHandTypeはintから生成できます。

```
// i = 0 -> gu
var choki = HandType.values().first { it.n == 0 })
// i = 1 -> choki
var choki = HandType.values().first { it.n == 1 })
// i = 2 -> pa
var choki = HandType.values().first { it.n == 2 })

enum class HandType(val n: Int) {
    gu(0),
    choki(1),
    pa(2)
}
```

https://qiita.com/stvjbz/items/04ab3e8a6c2cfcccca53

```
when (HandType.values().first { it.n == i % 3 }) {
    HandType.gu -> enemyHand.setImageResource( R.drawable.rock )
    HandType.choki -> enemyHand.setImageResource( R.drawable.scissors )
    HandType.pa -> enemyHand.setImageResource( R.drawable.paper )
}
```

2020-10-27 06:41 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +                when ( cpHand ) {
ここもintからenumを生成してwhenのところに入れてあげましょう

https://qiita.com/stvjbz/items/04ab3e8a6c2cfcccca53

```
val cpHand = HandType.values().first { it.n == (Math.random() * 3).toInt() }
when (cpHand) {
}
```

2020-10-27 06:41 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +                val gameResult = (cpHand - myHand + 3) % 3
ここも数値で結果を出すのであればenumを生成しよう

```
val gameResult = JankenResult.values().first { it.n == (cpHand.n - hand.n + 3) % 3 }
enum class JankenResult(val n: Int) {
    draw(0),
    win(1),
    lose(2)
}
```

2020-10-27 06:41 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +            rock.setImageResource(R.drawable.white)
rockだけここで`setImageResource `をしているのって理由とかある？

2020-11-09 00:08 UTC, taka0815basket commented
@mcz9mm 
修正遅くなってすみませんでした。コメントでもらったアドバイスを反映して修正しました。確認をお願いいたします。

2020-11-09 00:20 UTC, taka0815basket commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +            rock.setImageResource(R.drawable.white)
理由はないんですけど、いろいろ試していたらそれでうまくいったのでそのままにしている感じです。

2020-11-09 08:18 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +            rock.setImageResource(R.drawable.white)
ちゃんと原因を理解できる様になると良いね。
雰囲気で直すのと動きを理解して直すのでは根本的に違うので。

> 理由はないんですけど、いろいろ試していたらそれでうまくいったのでそのままにしている感じです。

2020-11-10 02:09 UTC, mcz9mm requested changes
あとちょい〜
使ってない箇所の整理とcpHandが１個余計に生成しているのでどちらか消してあげよう

レビュー出す前にアプリが動くかしっかりチェックしてみてね。
・何度も繰り返しできるか
・いろんな手でじゃんけんできるか
・レイアウトが崩れていないか

2020-11-10 02:09 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +        val cpHand = HandType.values().first { it.n == (Math.random() * 3).toInt() }
ここでアプリクラッシュしない？
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.janken, PID: 32609
    java.util.NoSuchElementException: Array contains no element matching the predicate.
        at com.example.janken.MainActivity.janken(MainActivity.kt:115)
        at com.example.janken.MainActivity$onCreate$3.onClick(MainActivity.kt:32)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

確認したら下記のように修正してみてください
```
val randomValue = (Math.random() * 3).toInt()
val cpHand = HandType.values().first { it.n == randomValue }
```

2020-11-10 02:09 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +        val myHand: Int = hand.n
使ってないなら消そう

2020-11-10 02:09 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +                when ( cpHand ) {
どっちか使ってないので消してください。

https://github.com/shinonome-inc/mobile_takafumi/pull/6/files#diff-65b4090b4f89d3597452fbe498f72801baa9d3ba558b812d488f0e52161f0859R39

2020-11-10 02:09 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +        fun fadeButton (handButton: ImageButton) {
ここのfunc全体のインデントずれているので修正してください。

2020-11-10 08:13 UTC, taka0815basket commented
課題4の修正ができたので確認のお願いいたします。

2020-11-10 08:37 UTC, mcz9mm requested changes
コードの整理＝コーディング規約だと思ってください。
書き方が推奨されているのでそれにあった形で書くと良いです。
不用意にスペースを空けるだけが整理ではないのでチェックしてみましょう。

・条件式ifやwhen等の後にはスペース
・コロンの後にスペース
など

詳しく載っているので確認してください。

https://developer.android.com/kotlin/style-guide?hl=ja

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +            fadeButton ( rock )
fadeButton(rock)

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +            janken ( HandType.gu )
janken(HandType.gu)

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +            fadeButton ( scissors )
fadeButton(scissors)

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +            janken ( HandType.choki )
janken(HandType.choki)

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +            fadeButton ( paper )
fadeButton(paper)

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +            janken ( HandType.pa )
janken(HandType.pa)

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +            if ( i >= 30 ){
if (i >= 30) {

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +                when ( gameResult ) {
when (gameResult) {

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +                handler.postDelayed ( runnable, 50 )
handler.postDelayed(runnable, 50)

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +        handler.post ( runnable )
handler.post(runnable)

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +enum class HandType( val n: Int ) {
enum class HandType(val n: Int) {

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +    gu(0 ),
gu(0),

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +    choki(1 ),
choki(1),

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +    pa(2 )
pa(2)

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +enum class JankenResult ( val n:Int ) {
enum class JankenResult(val n:Int) {

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +    draw(0 ),
draw(0),

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +    win(1) ,
win(1),

2020-11-10 08:37 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
>          fun fadeButton ( handButton: ImageButton ) {
インデント治ってないです

2020-11-10 23:57 UTC, taka0815basket commented
課題4の修正ができたので確認をお願いいたします。

2020-11-11 01:49 UTC, mcz9mm requested changes
細かいですが２箇所修正お願いします。

2020-11-11 01:49 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +    win(1) ,
ここ治ってないです。

`win(1) ,`→`win(1),`

2020-11-11 01:49 UTC, mcz9mm commented on kadai04/app/src/main/java/com/example/janken/MainActivity.kt
> +                when ( gameResult ) {
ここ治ってないです

`when ( gameResult ) {`→`when (gameResult) {`

2020-11-11 01:52 UTC, mcz9mm commented
もう少し丁寧なコミットメッセージを残せるといいね、

- 修正した箇所
- 内容
くらいはあるとわかりやすいよ。

<img width="833" alt="スクリーンショット 2020-11-11 10 46 58" src="https://user-images.githubusercontent.com/11751495/98755413-d31c0080-240b-11eb-97e1-d520ec434327.png">

2020-11-11 10:59 UTC, taka0815basket commented
課題4の修正ができました。再レビューをお願いいたします。

2020-11-11 11:30 UTC, merged